# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Counting Pebbles'
tagline:             'A history of ancient counting devices'
description:         'Exploration of our relationship with numbers throughout history, and the tools we use to count them.'

url:                 https://jtb.github.io/counting-pebbles
baseurl:             '/counting-pebbles'
paginate:            5

# About/contact
author:
  name:              Justin Brown
  url:               https://github.com/jtb
  email:             jbrown23+pebbles@gmail.com

# Custom vars
version:             0.0.1

plugins: [jekyll-paginate]
